baseURL = "https://ccschwan.github.io/100uncertainty/"
languageCode = "en-us"
title = "Uncertainty, Explainability & Fairness"
theme = "PaperMod"
defaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  tag = "tags"
